services:
  - type: web
    name: metacognizer
    runtime: node
    plan: starter
    buildCommand: npm install && cd server && npm install && cd ../client && npm install --include=dev && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: NODE_ENV
        value: production
